# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-06-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_footnote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_footnote_footnote', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
